language: android
   jdk: oraclejdk8
   sudo: false
   env:
   global:
     - ANDROID_TARGET=android-26
     - ANDROID_ABI=armeabi-v7a
   android:
     components:
     - tools
       - platform-tools
       - build-tools-26.0.1
       - android-26
       - android-22
       - extra-android-m2repository
       - sys-img-armeabi-v7a-android-26
        - extra-google-m2repository
        - extra-android-support
        - extra-google-google_play_services
           - extra-google-m2repository
          - extra-android-m2repository
           - addon-google_apis-google-26




before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script: ./gradlew connectedAndroidTest

#
#     script:
#       - ./gradlew build jacocoTestReport assembleAndroidTest
#       - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
#       - emulator -avd test -no-skin -no-window &
#       - android-wait-for-emulator
#       - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
#       - ./gradlew connectedCheck
#     after_success:
#       - bash <(curl -s https://codecov.io/bash)